// Code generated by protoc-gen-easyrpc-swift. DO NOT EDIT.
import easyRpc

public final class AgentServiceClient {
  private let t: any Transport
  public init(_ t: any Transport) { self.t = t }

  public func health(req: Agent_V1_HealthRequest) async throws -> Agent_V1_HealthResponse {
    let res = try await t.send(Request(url: "/agent.v1.AgentService/Health", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_HealthResponse(serializedBytes: res.body)
  }

  public func listSessions(req: Agent_V1_ListSessionsRequest) async throws -> Agent_V1_ListSessionsResponse {
    let res = try await t.send(Request(url: "/agent.v1.AgentService/ListSessions", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_ListSessionsResponse(serializedBytes: res.body)
  }

  public func createSession(req: Agent_V1_CreateSessionRequest) async throws -> Agent_V1_CreateSessionResponse {
    let res = try await t.send(Request(url: "/agent.v1.AgentService/CreateSession", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_CreateSessionResponse(serializedBytes: res.body)
  }

  public func getSession(req: Agent_V1_GetSessionRequest) async throws -> Agent_V1_GetSessionResponse {
    let res = try await t.send(Request(url: "/agent.v1.AgentService/GetSession", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_GetSessionResponse(serializedBytes: res.body)
  }

  public func deleteSession(req: Agent_V1_DeleteSessionRequest) async throws -> Agent_V1_DeleteSessionResponse {
    let res = try await t.send(Request(url: "/agent.v1.AgentService/DeleteSession", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_DeleteSessionResponse(serializedBytes: res.body)
  }

  public func listMessages(req: Agent_V1_ListMessagesRequest) async throws -> Agent_V1_ListMessagesResponse {
    let res = try await t.send(Request(url: "/agent.v1.AgentService/ListMessages", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_ListMessagesResponse(serializedBytes: res.body)
  }

  public func prompt(req: Agent_V1_PromptRequest) async throws -> AsyncThrowingStream<Agent_V1_PromptResponse, Error>
  { AsyncThrowingStream { cont in Task { do { let st = try await t.openStream(Request(url: "/agent.v1.AgentService/Prompt", body: try req.serializedData()))
    while let msg = await st.recv() { cont.yield(try Agent_V1_PromptResponse(serializedBytes: msg)) }
    if let e = st.lastError() { throw e }
    cont.finish() } catch { cont.finish(throwing: error) } } } }

  public func watchSession(req: Agent_V1_WatchSessionRequest) async throws -> AsyncThrowingStream<Agent_V1_WatchSessionResponse, Error>
  { AsyncThrowingStream { cont in Task { do { let st = try await t.openStream(Request(url: "/agent.v1.AgentService/WatchSession", body: try req.serializedData()))
    while let msg = await st.recv() { cont.yield(try Agent_V1_WatchSessionResponse(serializedBytes: msg)) }
    if let e = st.lastError() { throw e }
    cont.finish() } catch { cont.finish(throwing: error) } } } }

  public func watchSessions(req: Agent_V1_WatchSessionsRequest) async throws -> AsyncThrowingStream<Agent_V1_WatchSessionsResponse, Error>
  { AsyncThrowingStream { cont in Task { do { let st = try await t.openStream(Request(url: "/agent.v1.AgentService/WatchSessions", body: try req.serializedData()))
    while let msg = await st.recv() { cont.yield(try Agent_V1_WatchSessionsResponse(serializedBytes: msg)) }
    if let e = st.lastError() { throw e }
    cont.finish() } catch { cont.finish(throwing: error) } } } }

  public func fork(req: Agent_V1_ForkRequest) async throws -> Agent_V1_ForkResponse {
    let res = try await t.send(Request(url: "/agent.v1.AgentService/Fork", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_ForkResponse(serializedBytes: res.body)
  }

  public func rename(req: Agent_V1_RenameRequest) async throws -> Agent_V1_RenameResponse {
    let res = try await t.send(Request(url: "/agent.v1.AgentService/Rename", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_RenameResponse(serializedBytes: res.body)
  }

  public func setModel(req: Agent_V1_SetModelRequest) async throws -> Agent_V1_SetModelResponse {
    let res = try await t.send(Request(url: "/agent.v1.AgentService/SetModel", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_SetModelResponse(serializedBytes: res.body)
  }

  public func undo(req: Agent_V1_UndoRequest) async throws -> Agent_V1_UndoResponse {
    let res = try await t.send(Request(url: "/agent.v1.AgentService/Undo", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_UndoResponse(serializedBytes: res.body)
  }

  public func state(req: Agent_V1_StateRequest) async throws -> Agent_V1_StateResponse {
    let res = try await t.send(Request(url: "/agent.v1.AgentService/State", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_StateResponse(serializedBytes: res.body)
  }

  public func mailbox(req: Agent_V1_MailboxRequest) async throws -> Agent_V1_MailboxResponse {
    let res = try await t.send(Request(url: "/agent.v1.AgentService/Mailbox", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_MailboxResponse(serializedBytes: res.body)
  }

  public func updateSettings(req: Agent_V1_UpdateSettingsRequest) async throws -> Agent_V1_UpdateSettingsResponse {
    let res = try await t.send(Request(url: "/agent.v1.AgentService/UpdateSettings", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_UpdateSettingsResponse(serializedBytes: res.body)
  }

  public func interrupt(req: Agent_V1_InterruptRequest) async throws -> Agent_V1_InterruptResponse {
    let res = try await t.send(Request(url: "/agent.v1.AgentService/Interrupt", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_InterruptResponse(serializedBytes: res.body)
  }

  public func compact(req: Agent_V1_CompactRequest) async throws -> Agent_V1_CompactResponse {
    let res = try await t.send(Request(url: "/agent.v1.AgentService/Compact", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_CompactResponse(serializedBytes: res.body)
  }

  public func listProviders(req: Agent_V1_ListProvidersRequest) async throws -> Agent_V1_ListProvidersResponse {
    let res = try await t.send(Request(url: "/agent.v1.AgentService/ListProviders", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_ListProvidersResponse(serializedBytes: res.body)
  }

  public func listProvidersCatalog(req: Agent_V1_ListProvidersCatalogRequest) async throws -> Agent_V1_ListProvidersCatalogResponse {
    let res = try await t.send(Request(url: "/agent.v1.AgentService/ListProvidersCatalog", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_ListProvidersCatalogResponse(serializedBytes: res.body)
  }

  public func registerProvider(req: Agent_V1_RegisterProviderRequest) async throws -> Agent_V1_RegisterProviderResponse {
    let res = try await t.send(Request(url: "/agent.v1.AgentService/RegisterProvider", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_RegisterProviderResponse(serializedBytes: res.body)
  }

  public func discoverGatewayModels(req: Agent_V1_DiscoverGatewayModelsRequest) async throws -> Agent_V1_DiscoverGatewayModelsResponse {
    let res = try await t.send(Request(url: "/agent.v1.AgentService/DiscoverGatewayModels", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_DiscoverGatewayModelsResponse(serializedBytes: res.body)
  }

  public func deleteProvider(req: Agent_V1_DeleteProviderRequest) async throws -> Agent_V1_DeleteProviderResponse {
    let res = try await t.send(Request(url: "/agent.v1.AgentService/DeleteProvider", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_DeleteProviderResponse(serializedBytes: res.body)
  }

  public func testProvider(req: Agent_V1_TestProviderRequest) async throws -> Agent_V1_TestProviderResponse {
    let res = try await t.send(Request(url: "/agent.v1.AgentService/TestProvider", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_TestProviderResponse(serializedBytes: res.body)
  }

  public func listModels(req: Agent_V1_ListModelsRequest) async throws -> Agent_V1_ListModelsResponse {
    let res = try await t.send(Request(url: "/agent.v1.AgentService/ListModels", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_ListModelsResponse(serializedBytes: res.body)
  }

  public func listPresets(req: Agent_V1_ListPresetsRequest) async throws -> Agent_V1_ListPresetsResponse {
    let res = try await t.send(Request(url: "/agent.v1.AgentService/ListPresets", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_ListPresetsResponse(serializedBytes: res.body)
  }

  public func upsertPreset(req: Agent_V1_UpsertPresetRequest) async throws -> Agent_V1_UpsertPresetResponse {
    let res = try await t.send(Request(url: "/agent.v1.AgentService/UpsertPreset", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_UpsertPresetResponse(serializedBytes: res.body)
  }

  public func deletePreset(req: Agent_V1_DeletePresetRequest) async throws -> Agent_V1_DeletePresetResponse {
    let res = try await t.send(Request(url: "/agent.v1.AgentService/DeletePreset", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_DeletePresetResponse(serializedBytes: res.body)
  }

  public func previewPreset(req: Agent_V1_PreviewPresetRequest) async throws -> Agent_V1_PreviewPresetResponse {
    let res = try await t.send(Request(url: "/agent.v1.AgentService/PreviewPreset", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_PreviewPresetResponse(serializedBytes: res.body)
  }

  public func getConfig(req: Agent_V1_GetConfigRequest) async throws -> Agent_V1_GetConfigResponse {
    let res = try await t.send(Request(url: "/agent.v1.AgentService/GetConfig", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_GetConfigResponse(serializedBytes: res.body)
  }

  public func setConfig(req: Agent_V1_SetConfigRequest) async throws -> Agent_V1_SetConfigResponse {
    let res = try await t.send(Request(url: "/agent.v1.AgentService/SetConfig", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_SetConfigResponse(serializedBytes: res.body)
  }

  public func listTools(req: Agent_V1_ListToolsRequest) async throws -> Agent_V1_ListToolsResponse {
    let res = try await t.send(Request(url: "/agent.v1.AgentService/ListTools", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_ListToolsResponse(serializedBytes: res.body)
  }

  public func getToolConfig(req: Agent_V1_GetToolConfigRequest) async throws -> Agent_V1_GetToolConfigResponse {
    let res = try await t.send(Request(url: "/agent.v1.AgentService/GetToolConfig", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_GetToolConfigResponse(serializedBytes: res.body)
  }

  public func setToolConfig(req: Agent_V1_SetToolConfigRequest) async throws -> Agent_V1_SetToolConfigResponse {
    let res = try await t.send(Request(url: "/agent.v1.AgentService/SetToolConfig", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_SetToolConfigResponse(serializedBytes: res.body)
  }

  public func setExtensionConfig(req: Agent_V1_SetExtensionConfigRequest) async throws -> Agent_V1_SetExtensionConfigResponse {
    let res = try await t.send(Request(url: "/agent.v1.AgentService/SetExtensionConfig", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_SetExtensionConfigResponse(serializedBytes: res.body)
  }

  public func uploadFile(req: Agent_V1_UploadFileRequest) async throws -> Agent_V1_UploadFileResponse {
    let res = try await t.send(Request(url: "/agent.v1.AgentService/UploadFile", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_UploadFileResponse(serializedBytes: res.body)
  }

  public func ingestFile(req: Agent_V1_IngestFileRequest) async throws -> Agent_V1_IngestFileResponse {
    let res = try await t.send(Request(url: "/agent.v1.AgentService/IngestFile", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_IngestFileResponse(serializedBytes: res.body)
  }

  public func getFile(req: Agent_V1_GetFileRequest) async throws -> Agent_V1_GetFileResponse {
    let res = try await t.send(Request(url: "/agent.v1.AgentService/GetFile", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_GetFileResponse(serializedBytes: res.body)
  }

  public func getFileMeta(req: Agent_V1_GetFileMetaRequest) async throws -> Agent_V1_GetFileMetaResponse {
    let res = try await t.send(Request(url: "/agent.v1.AgentService/GetFileMeta", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_GetFileMetaResponse(serializedBytes: res.body)
  }

  public func getAgentConfig(req: Agent_V1_GetAgentConfigRequest) async throws -> Agent_V1_GetAgentConfigResponse {
    let res = try await t.send(Request(url: "/agent.v1.AgentService/GetAgentConfig", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_GetAgentConfigResponse(serializedBytes: res.body)
  }

}