// Code generated by protoc-gen-easyrpc-swift. DO NOT EDIT.
import easyRpc

public final class AdminServiceClient {
  private let t: any Transport
  public init(_ t: any Transport) { self.t = t }

  public func listTenants(req: Agent_V1_ListTenantsRequest) async throws -> Agent_V1_ListTenantsResponse {
    let res = try await t.send(Request(url: "/agent.v1.AdminService/ListTenants", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_ListTenantsResponse(serializedBytes: res.body)
  }

  public func createTenant(req: Agent_V1_CreateTenantRequest) async throws -> Agent_V1_CreateTenantResponse {
    let res = try await t.send(Request(url: "/agent.v1.AdminService/CreateTenant", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_CreateTenantResponse(serializedBytes: res.body)
  }

  public func updateTenant(req: Agent_V1_UpdateTenantRequest) async throws -> Agent_V1_UpdateTenantResponse {
    let res = try await t.send(Request(url: "/agent.v1.AdminService/UpdateTenant", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_UpdateTenantResponse(serializedBytes: res.body)
  }

  public func deleteTenant(req: Agent_V1_DeleteTenantRequest) async throws -> Agent_V1_DeleteTenantResponse {
    let res = try await t.send(Request(url: "/agent.v1.AdminService/DeleteTenant", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_DeleteTenantResponse(serializedBytes: res.body)
  }

  public func issueTenantToken(req: Agent_V1_IssueTenantTokenRequest) async throws -> Agent_V1_IssueTenantTokenResponse {
    let res = try await t.send(Request(url: "/agent.v1.AdminService/IssueTenantToken", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_IssueTenantTokenResponse(serializedBytes: res.body)
  }

  public func listTenantTokens(req: Agent_V1_ListTenantTokensRequest) async throws -> Agent_V1_ListTenantTokensResponse {
    let res = try await t.send(Request(url: "/agent.v1.AdminService/ListTenantTokens", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_ListTenantTokensResponse(serializedBytes: res.body)
  }

  public func revokeTenantToken(req: Agent_V1_RevokeTenantTokenRequest) async throws -> Agent_V1_RevokeTenantTokenResponse {
    let res = try await t.send(Request(url: "/agent.v1.AdminService/RevokeTenantToken", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_RevokeTenantTokenResponse(serializedBytes: res.body)
  }

  public func rotateTenantToken(req: Agent_V1_RotateTenantTokenRequest) async throws -> Agent_V1_RotateTenantTokenResponse {
    let res = try await t.send(Request(url: "/agent.v1.AdminService/RotateTenantToken", body: try req.serializedData()))
    if let e = res.error { throw e }
    return try Agent_V1_RotateTenantTokenResponse(serializedBytes: res.body)
  }

}