// Code generated by protoc-gen-easyrpc-swift. DO NOT EDIT.
import easyRpc

public final class AgentServiceClient {
  private let t: any Transport
  public init(_ t: any Transport) { self.t = t }
  public var lastTrailers: Headers = [:]
  public var lastStream: (any Stream)?

  public func health(req: Agent_V1_HealthRequest, kind: String = "proto") async throws -> Agent_V1_HealthResponse {
    let ct = contentTypeFor(false, kind)
    let res = try await t.send(Request(url: "/agent.v1.AgentService/Health", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))
    self.lastTrailers = res.trailers
    if let e = res.error { throw e }
    return try decodeMsg(res.body, Agent_V1_HealthResponse.self, kind)
  }

  public func listSessions(req: Agent_V1_ListSessionsRequest, kind: String = "proto") async throws -> Agent_V1_ListSessionsResponse {
    let ct = contentTypeFor(false, kind)
    let res = try await t.send(Request(url: "/agent.v1.AgentService/ListSessions", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))
    self.lastTrailers = res.trailers
    if let e = res.error { throw e }
    return try decodeMsg(res.body, Agent_V1_ListSessionsResponse.self, kind)
  }

  public func createSession(req: Agent_V1_CreateSessionRequest, kind: String = "proto") async throws -> Agent_V1_CreateSessionResponse {
    let ct = contentTypeFor(false, kind)
    let res = try await t.send(Request(url: "/agent.v1.AgentService/CreateSession", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))
    self.lastTrailers = res.trailers
    if let e = res.error { throw e }
    return try decodeMsg(res.body, Agent_V1_CreateSessionResponse.self, kind)
  }

  public func getSession(req: Agent_V1_GetSessionRequest, kind: String = "proto") async throws -> Agent_V1_GetSessionResponse {
    let ct = contentTypeFor(false, kind)
    let res = try await t.send(Request(url: "/agent.v1.AgentService/GetSession", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))
    self.lastTrailers = res.trailers
    if let e = res.error { throw e }
    return try decodeMsg(res.body, Agent_V1_GetSessionResponse.self, kind)
  }

  public func deleteSession(req: Agent_V1_DeleteSessionRequest, kind: String = "proto") async throws -> Agent_V1_DeleteSessionResponse {
    let ct = contentTypeFor(false, kind)
    let res = try await t.send(Request(url: "/agent.v1.AgentService/DeleteSession", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))
    self.lastTrailers = res.trailers
    if let e = res.error { throw e }
    return try decodeMsg(res.body, Agent_V1_DeleteSessionResponse.self, kind)
  }

  public func listMessages(req: Agent_V1_ListMessagesRequest, kind: String = "proto") async throws -> Agent_V1_ListMessagesResponse {
    let ct = contentTypeFor(false, kind)
    let res = try await t.send(Request(url: "/agent.v1.AgentService/ListMessages", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))
    self.lastTrailers = res.trailers
    if let e = res.error { throw e }
    return try decodeMsg(res.body, Agent_V1_ListMessagesResponse.self, kind)
  }

  public func prompt(req: Agent_V1_PromptRequest, kind: String = "proto") async throws -> AsyncThrowingStream<Agent_V1_PromptResponse, Error>
  { AsyncThrowingStream { cont in Task { do { let ct = contentTypeFor(true, kind); let st = try await t.openStream(Request(url: "/agent.v1.AgentService/Prompt", headers: ["content-type": [ct]], body: frame(try encodeMsg(req, kind))))
    self.lastStream = st
    while let msg = await st.recv() { cont.yield(try decodeMsg(msg, Agent_V1_PromptResponse.self, kind)) }
    if let e = st.lastError() { throw e }
    cont.finish() } catch { cont.finish(throwing: error) } } } }

  public func watchSession(req: Agent_V1_WatchSessionRequest, kind: String = "proto") async throws -> AsyncThrowingStream<Agent_V1_WatchSessionResponse, Error>
  { AsyncThrowingStream { cont in Task { do { let ct = contentTypeFor(true, kind); let st = try await t.openStream(Request(url: "/agent.v1.AgentService/WatchSession", headers: ["content-type": [ct]], body: frame(try encodeMsg(req, kind))))
    self.lastStream = st
    while let msg = await st.recv() { cont.yield(try decodeMsg(msg, Agent_V1_WatchSessionResponse.self, kind)) }
    if let e = st.lastError() { throw e }
    cont.finish() } catch { cont.finish(throwing: error) } } } }

  public func watchSessions(req: Agent_V1_WatchSessionsRequest, kind: String = "proto") async throws -> AsyncThrowingStream<Agent_V1_WatchSessionsResponse, Error>
  { AsyncThrowingStream { cont in Task { do { let ct = contentTypeFor(true, kind); let st = try await t.openStream(Request(url: "/agent.v1.AgentService/WatchSessions", headers: ["content-type": [ct]], body: frame(try encodeMsg(req, kind))))
    self.lastStream = st
    while let msg = await st.recv() { cont.yield(try decodeMsg(msg, Agent_V1_WatchSessionsResponse.self, kind)) }
    if let e = st.lastError() { throw e }
    cont.finish() } catch { cont.finish(throwing: error) } } } }

  public func fork(req: Agent_V1_ForkRequest, kind: String = "proto") async throws -> Agent_V1_ForkResponse {
    let ct = contentTypeFor(false, kind)
    let res = try await t.send(Request(url: "/agent.v1.AgentService/Fork", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))
    self.lastTrailers = res.trailers
    if let e = res.error { throw e }
    return try decodeMsg(res.body, Agent_V1_ForkResponse.self, kind)
  }

  public func rename(req: Agent_V1_RenameRequest, kind: String = "proto") async throws -> Agent_V1_RenameResponse {
    let ct = contentTypeFor(false, kind)
    let res = try await t.send(Request(url: "/agent.v1.AgentService/Rename", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))
    self.lastTrailers = res.trailers
    if let e = res.error { throw e }
    return try decodeMsg(res.body, Agent_V1_RenameResponse.self, kind)
  }

  public func setModel(req: Agent_V1_SetModelRequest, kind: String = "proto") async throws -> Agent_V1_SetModelResponse {
    let ct = contentTypeFor(false, kind)
    let res = try await t.send(Request(url: "/agent.v1.AgentService/SetModel", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))
    self.lastTrailers = res.trailers
    if let e = res.error { throw e }
    return try decodeMsg(res.body, Agent_V1_SetModelResponse.self, kind)
  }

  public func undo(req: Agent_V1_UndoRequest, kind: String = "proto") async throws -> Agent_V1_UndoResponse {
    let ct = contentTypeFor(false, kind)
    let res = try await t.send(Request(url: "/agent.v1.AgentService/Undo", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))
    self.lastTrailers = res.trailers
    if let e = res.error { throw e }
    return try decodeMsg(res.body, Agent_V1_UndoResponse.self, kind)
  }

  public func state(req: Agent_V1_StateRequest, kind: String = "proto") async throws -> Agent_V1_StateResponse {
    let ct = contentTypeFor(false, kind)
    let res = try await t.send(Request(url: "/agent.v1.AgentService/State", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))
    self.lastTrailers = res.trailers
    if let e = res.error { throw e }
    return try decodeMsg(res.body, Agent_V1_StateResponse.self, kind)
  }

  public func mailbox(req: Agent_V1_MailboxRequest, kind: String = "proto") async throws -> Agent_V1_MailboxResponse {
    let ct = contentTypeFor(false, kind)
    let res = try await t.send(Request(url: "/agent.v1.AgentService/Mailbox", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))
    self.lastTrailers = res.trailers
    if let e = res.error { throw e }
    return try decodeMsg(res.body, Agent_V1_MailboxResponse.self, kind)
  }

  public func updateSettings(req: Agent_V1_UpdateSettingsRequest, kind: String = "proto") async throws -> Agent_V1_UpdateSettingsResponse {
    let ct = contentTypeFor(false, kind)
    let res = try await t.send(Request(url: "/agent.v1.AgentService/UpdateSettings", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))
    self.lastTrailers = res.trailers
    if let e = res.error { throw e }
    return try decodeMsg(res.body, Agent_V1_UpdateSettingsResponse.self, kind)
  }

  public func interrupt(req: Agent_V1_InterruptRequest, kind: String = "proto") async throws -> Agent_V1_InterruptResponse {
    let ct = contentTypeFor(false, kind)
    let res = try await t.send(Request(url: "/agent.v1.AgentService/Interrupt", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))
    self.lastTrailers = res.trailers
    if let e = res.error { throw e }
    return try decodeMsg(res.body, Agent_V1_InterruptResponse.self, kind)
  }

  public func compact(req: Agent_V1_CompactRequest, kind: String = "proto") async throws -> Agent_V1_CompactResponse {
    let ct = contentTypeFor(false, kind)
    let res = try await t.send(Request(url: "/agent.v1.AgentService/Compact", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))
    self.lastTrailers = res.trailers
    if let e = res.error { throw e }
    return try decodeMsg(res.body, Agent_V1_CompactResponse.self, kind)
  }

  public func listProviders(req: Agent_V1_ListProvidersRequest, kind: String = "proto") async throws -> Agent_V1_ListProvidersResponse {
    let ct = contentTypeFor(false, kind)
    let res = try await t.send(Request(url: "/agent.v1.AgentService/ListProviders", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))
    self.lastTrailers = res.trailers
    if let e = res.error { throw e }
    return try decodeMsg(res.body, Agent_V1_ListProvidersResponse.self, kind)
  }

  public func listProvidersCatalog(req: Agent_V1_ListProvidersCatalogRequest, kind: String = "proto") async throws -> Agent_V1_ListProvidersCatalogResponse {
    let ct = contentTypeFor(false, kind)
    let res = try await t.send(Request(url: "/agent.v1.AgentService/ListProvidersCatalog", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))
    self.lastTrailers = res.trailers
    if let e = res.error { throw e }
    return try decodeMsg(res.body, Agent_V1_ListProvidersCatalogResponse.self, kind)
  }

  public func registerProvider(req: Agent_V1_RegisterProviderRequest, kind: String = "proto") async throws -> Agent_V1_RegisterProviderResponse {
    let ct = contentTypeFor(false, kind)
    let res = try await t.send(Request(url: "/agent.v1.AgentService/RegisterProvider", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))
    self.lastTrailers = res.trailers
    if let e = res.error { throw e }
    return try decodeMsg(res.body, Agent_V1_RegisterProviderResponse.self, kind)
  }

  public func deleteProvider(req: Agent_V1_DeleteProviderRequest, kind: String = "proto") async throws -> Agent_V1_DeleteProviderResponse {
    let ct = contentTypeFor(false, kind)
    let res = try await t.send(Request(url: "/agent.v1.AgentService/DeleteProvider", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))
    self.lastTrailers = res.trailers
    if let e = res.error { throw e }
    return try decodeMsg(res.body, Agent_V1_DeleteProviderResponse.self, kind)
  }

  public func testProvider(req: Agent_V1_TestProviderRequest, kind: String = "proto") async throws -> Agent_V1_TestProviderResponse {
    let ct = contentTypeFor(false, kind)
    let res = try await t.send(Request(url: "/agent.v1.AgentService/TestProvider", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))
    self.lastTrailers = res.trailers
    if let e = res.error { throw e }
    return try decodeMsg(res.body, Agent_V1_TestProviderResponse.self, kind)
  }

  public func listModels(req: Agent_V1_ListModelsRequest, kind: String = "proto") async throws -> Agent_V1_ListModelsResponse {
    let ct = contentTypeFor(false, kind)
    let res = try await t.send(Request(url: "/agent.v1.AgentService/ListModels", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))
    self.lastTrailers = res.trailers
    if let e = res.error { throw e }
    return try decodeMsg(res.body, Agent_V1_ListModelsResponse.self, kind)
  }

  public func listPresets(req: Agent_V1_ListPresetsRequest, kind: String = "proto") async throws -> Agent_V1_ListPresetsResponse {
    let ct = contentTypeFor(false, kind)
    let res = try await t.send(Request(url: "/agent.v1.AgentService/ListPresets", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))
    self.lastTrailers = res.trailers
    if let e = res.error { throw e }
    return try decodeMsg(res.body, Agent_V1_ListPresetsResponse.self, kind)
  }

  public func upsertPreset(req: Agent_V1_UpsertPresetRequest, kind: String = "proto") async throws -> Agent_V1_UpsertPresetResponse {
    let ct = contentTypeFor(false, kind)
    let res = try await t.send(Request(url: "/agent.v1.AgentService/UpsertPreset", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))
    self.lastTrailers = res.trailers
    if let e = res.error { throw e }
    return try decodeMsg(res.body, Agent_V1_UpsertPresetResponse.self, kind)
  }

  public func deletePreset(req: Agent_V1_DeletePresetRequest, kind: String = "proto") async throws -> Agent_V1_DeletePresetResponse {
    let ct = contentTypeFor(false, kind)
    let res = try await t.send(Request(url: "/agent.v1.AgentService/DeletePreset", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))
    self.lastTrailers = res.trailers
    if let e = res.error { throw e }
    return try decodeMsg(res.body, Agent_V1_DeletePresetResponse.self, kind)
  }

  public func previewPreset(req: Agent_V1_PreviewPresetRequest, kind: String = "proto") async throws -> Agent_V1_PreviewPresetResponse {
    let ct = contentTypeFor(false, kind)
    let res = try await t.send(Request(url: "/agent.v1.AgentService/PreviewPreset", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))
    self.lastTrailers = res.trailers
    if let e = res.error { throw e }
    return try decodeMsg(res.body, Agent_V1_PreviewPresetResponse.self, kind)
  }

  public func getConfig(req: Agent_V1_GetConfigRequest, kind: String = "proto") async throws -> Agent_V1_GetConfigResponse {
    let ct = contentTypeFor(false, kind)
    let res = try await t.send(Request(url: "/agent.v1.AgentService/GetConfig", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))
    self.lastTrailers = res.trailers
    if let e = res.error { throw e }
    return try decodeMsg(res.body, Agent_V1_GetConfigResponse.self, kind)
  }

  public func setConfig(req: Agent_V1_SetConfigRequest, kind: String = "proto") async throws -> Agent_V1_SetConfigResponse {
    let ct = contentTypeFor(false, kind)
    let res = try await t.send(Request(url: "/agent.v1.AgentService/SetConfig", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))
    self.lastTrailers = res.trailers
    if let e = res.error { throw e }
    return try decodeMsg(res.body, Agent_V1_SetConfigResponse.self, kind)
  }

  public func listTools(req: Agent_V1_ListToolsRequest, kind: String = "proto") async throws -> Agent_V1_ListToolsResponse {
    let ct = contentTypeFor(false, kind)
    let res = try await t.send(Request(url: "/agent.v1.AgentService/ListTools", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))
    self.lastTrailers = res.trailers
    if let e = res.error { throw e }
    return try decodeMsg(res.body, Agent_V1_ListToolsResponse.self, kind)
  }

  public func getToolConfig(req: Agent_V1_GetToolConfigRequest, kind: String = "proto") async throws -> Agent_V1_GetToolConfigResponse {
    let ct = contentTypeFor(false, kind)
    let res = try await t.send(Request(url: "/agent.v1.AgentService/GetToolConfig", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))
    self.lastTrailers = res.trailers
    if let e = res.error { throw e }
    return try decodeMsg(res.body, Agent_V1_GetToolConfigResponse.self, kind)
  }

  public func setToolConfig(req: Agent_V1_SetToolConfigRequest, kind: String = "proto") async throws -> Agent_V1_SetToolConfigResponse {
    let ct = contentTypeFor(false, kind)
    let res = try await t.send(Request(url: "/agent.v1.AgentService/SetToolConfig", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))
    self.lastTrailers = res.trailers
    if let e = res.error { throw e }
    return try decodeMsg(res.body, Agent_V1_SetToolConfigResponse.self, kind)
  }

  public func setExtensionConfig(req: Agent_V1_SetExtensionConfigRequest, kind: String = "proto") async throws -> Agent_V1_SetExtensionConfigResponse {
    let ct = contentTypeFor(false, kind)
    let res = try await t.send(Request(url: "/agent.v1.AgentService/SetExtensionConfig", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))
    self.lastTrailers = res.trailers
    if let e = res.error { throw e }
    return try decodeMsg(res.body, Agent_V1_SetExtensionConfigResponse.self, kind)
  }

  public func uploadFile(req: Agent_V1_UploadFileRequest, kind: String = "proto") async throws -> Agent_V1_UploadFileResponse {
    let ct = contentTypeFor(false, kind)
    let res = try await t.send(Request(url: "/agent.v1.AgentService/UploadFile", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))
    self.lastTrailers = res.trailers
    if let e = res.error { throw e }
    return try decodeMsg(res.body, Agent_V1_UploadFileResponse.self, kind)
  }

  public func ingestFile(req: Agent_V1_IngestFileRequest, kind: String = "proto") async throws -> Agent_V1_IngestFileResponse {
    let ct = contentTypeFor(false, kind)
    let res = try await t.send(Request(url: "/agent.v1.AgentService/IngestFile", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))
    self.lastTrailers = res.trailers
    if let e = res.error { throw e }
    return try decodeMsg(res.body, Agent_V1_IngestFileResponse.self, kind)
  }

  public func getFile(req: Agent_V1_GetFileRequest, kind: String = "proto") async throws -> Agent_V1_GetFileResponse {
    let ct = contentTypeFor(false, kind)
    let res = try await t.send(Request(url: "/agent.v1.AgentService/GetFile", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))
    self.lastTrailers = res.trailers
    if let e = res.error { throw e }
    return try decodeMsg(res.body, Agent_V1_GetFileResponse.self, kind)
  }

  public func getFileMeta(req: Agent_V1_GetFileMetaRequest, kind: String = "proto") async throws -> Agent_V1_GetFileMetaResponse {
    let ct = contentTypeFor(false, kind)
    let res = try await t.send(Request(url: "/agent.v1.AgentService/GetFileMeta", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))
    self.lastTrailers = res.trailers
    if let e = res.error { throw e }
    return try decodeMsg(res.body, Agent_V1_GetFileMetaResponse.self, kind)
  }

  public func getFileStream(req: Agent_V1_GetFileRequest, kind: String = "proto") async throws -> AsyncThrowingStream<Agent_V1_FileChunk, Error>
  { AsyncThrowingStream { cont in Task { do { let ct = contentTypeFor(true, kind); let st = try await t.openStream(Request(url: "/agent.v1.AgentService/GetFileStream", headers: ["content-type": [ct]], body: frame(try encodeMsg(req, kind))))
    self.lastStream = st
    while let msg = await st.recv() { cont.yield(try decodeMsg(msg, Agent_V1_FileChunk.self, kind)) }
    if let e = st.lastError() { throw e }
    cont.finish() } catch { cont.finish(throwing: error) } } } }

  public func getAgentConfig(req: Agent_V1_GetAgentConfigRequest, kind: String = "proto") async throws -> Agent_V1_GetAgentConfigResponse {
    let ct = contentTypeFor(false, kind)
    let res = try await t.send(Request(url: "/agent.v1.AgentService/GetAgentConfig", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))
    self.lastTrailers = res.trailers
    if let e = res.error { throw e }
    return try decodeMsg(res.body, Agent_V1_GetAgentConfigResponse.self, kind)
  }

}